# Generated by Django 3.2.6 on 2022-08-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzeriaprofile',
            old_name='username',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='pizzeriaprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='pizzeriaprofile',
            name='profile_pic',
        ),
    ]
