# Generated by Django 3.2.6 on 2022-08-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('paris', 'paris'), ('new York', 'new York'), ('sidi aich', 'sidi aich'), ('roma', 'roma'), ('manchester', 'manchester')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Pizza Marguerita', 'Pizza Marguerita'), ('Pizza Marguerita', 'Pizza Marguerita'), ('Neapolitan Pizza', 'Neapolitan Pizza'), ('Chicago Pizza', 'Chicago Pizza'), ('Greek Pizza', 'Greek Pizza'), ('custom', 'custom')], max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('pic', models.ImageField(default=None, null=True, upload_to='pizza-pics')),
                ('custom', models.BooleanField(default=False)),
                ('pizzeria', models.ManyToManyField(related_name='pizzas', to='pizza.Pizzeria')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('olives', 'olives'), ('cheese', 'cheese'), ('Chorizo', 'Chorizo'), ('pineapple', 'pineapple'), ('Camembert', 'Camembert'), ('Provolone', 'Provolone')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('pizza', models.ManyToManyField(blank=True, related_name='ingredients', to='pizza.Pizza')),
            ],
        ),
    ]
