# Generated by Django 3.2.6 on 2022-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizza_pizzeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='pizza',
            field=models.ManyToManyField(related_name='ingredients', to='pizza.Pizza'),
        ),
    ]
