# Generated by Django 3.2.6 on 2022-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_ingredient_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pic',
            field=models.ImageField(default=None, null=True, upload_to='pizza-pics'),
        ),
    ]
